### ISSUE TITLE
README contains a stale link.

### ISSUE THREAD

**Issue by kfogel** [LibertyDSNP/spec#118]
The `README.md` has a stale link in the first paragraph.  Look for the second instance of the word "[here](https://github.com/LibertyDSNP/spec/blob/main/tree/main/pages)", linking to `https://github.com/LibertyDSNP/spec/blob/main/tree/main/pages`, which currently gets "404 Not Found".

(I ran into this when I was trying to find a printable PDF of the latest full spec, by the way.  Does such a thing exist?)

**Comment by kfogel** [comment]
@claireolmstead and @enddynayn, I flagged you as a best guess, but please re-route if needed of course.

**Comment by wilwade** [comment]
Closed by #121

**Comment by kfogel** [comment]
Thanks, @wilwade.
