### ISSUE TITLE
Incorrect Mime Types

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/spec#126]
### Steps to reproduce
Some of the mime types on the attachments page are incorrect.

https://github.com/LibertyDSNP/spec/blob/main/pages/ActivityContent/Associated/Attachments.md

### Expected behaviour
- `audio/mp3` -> `audio/mpeg`
- `image/jpg` -> `image/jpeg` (Or remove for just JPEG the line above it)

**Comment by waylandli** [comment]
I also made a pr within the sdk to match the changes being made to the spec
