### ISSUE TITLE
DIP-148 Rename DSNP Announcement URI to DSNP Content URI

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/spec#148]
# Abstract

While updating #145, we realized that the DSNP Announcement URI is a misnomer. It is instead a Content URI and should be identified as such in the spec.

# Motivation

- Clarity in names is important.

# Specification Pull Request

Current change pull request: TODO

## Additional Actions

- [ ] Create story in sdk-ts to update naming
- [ ] Create story in activity-content to update requirement
- [ ] Create story in activity-content-java to update requirement
- [ ] Create story in activity-content-swift to update requirement

# Rationale

The alternative of leaving it with a poor name made it hard to define.

# Backwards Compatibility

- Any sdk packages that use named parameters might need to be updated.

# Security Considerations

- Increases security in that it is a more precise name

# Dependencies

- #158

# References

- https://github.com/LibertyDSNP/spec/issues/145#issuecomment-1076659427

# Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by shannonwells** [comment]
👍
