### ISSUE TITLE
Style extneral link in sidebar

### ISSUE THREAD

**Issue by mehtaishita** [LibertyDSNP/spec#155]
## Acceptance Criteria
- [ ] External links in the sidebar (i.e. Developer Portal) should have the same formatting as the other items

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/40524916/160438350-09741ab1-3371-4edf-880d-0c604460dd8b.png">

**Comment by saraswatpuneet** [comment]
It looks ok to me, noted in this view in main branch 
@mehtaishita  is the issue about offset in Developer Portal ?

Current image from main
![image](https://user-images.githubusercontent.com/61435908/161873680-7318c33c-5949-4d1e-a3de-5855c411a348.png)
