### ISSUE TITLE
DIP-169 Block/Unblock Graph Changes

### ISSUE THREAD

**Issue by dopatraman** [LibertyDSNP/spec#169]
# Abstract

A proposal to extend our protocol to include an announcement type for "blocking" and "unblocking" users.

# Motivation

- Accommodate the expectations of users from social networks that support this functionality

# Specification Pull Request

Current change pull request: #170 

# Rationale

Users of centralized social networks will use DSNP with certain expectations, one of which likely will be having the ability to block / unblock followers. One way to do this is extend our announcement type offering to include explicit Block and Unblock  types.

## Open Questions
- Is it possible to leverage ActivityStreams to accommodate this feature?
- Given that announcers have static IDs, will it be possible for users to block them? What implications does that have for how the entire network functions?
- Does this need to be a spec-level feature at all?

# Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

# Reference 
https://docs.google.com/document/d/1ON2cJRvZYFWmTD6VzLXNnt2B4CijrdYfWap9JH6uw9E/edit

**Comment by wilwade** [comment]
@dopatraman could you move the information from the Google Doc into the issue? Some of that should be discussed here.

Also I think we need to update the issue title to follow the DIP format.

**Comment by wilwade** [comment]
Closing for now. We are going to think more about this with respect to private graph
