### ISSUE TITLE
[DSNP] Frequency Batch Validation

### ISSUE THREAD

**Issue by cchen818** [LibertyDSNP/spec#189]
Should be merged into
- `dsnp-on-mrc` Branch
- For PR: https://github.com/LibertyDSNP/spec/pull/197
- Fills out `pages/MRC/Validation.md`
- Effectively the version of https://github.com/LibertyDSNP/spec/blob/main/pages/Ethereum/Validation.md for Frequency

**Batch Publication Validation**

As a user, I need to know how to confirm the downloaded batch file is valid.

**Announcement Validation**

As a user, I need to know how to confirm the announcement in a given batch is valid.

**Announcement Duplicates**

As a user, I need to know how to handle duplicated announcements in a given batch or across batches.

**Comment by shannonwells** [comment]
This may need to be broken up into >1 issue.  Also is this for implementing these features or are these documentation requests?

**Comment by aramikm** [comment]
It seems like there are different ways to handle dedup depending on who is the end user
1- if a service then they can basically have a db for dedup
2- an end user in a mobile app might not be able to store all announcement ids to dedup and might need other ways to handle it

**Comment by wilwade** [comment]
Closed by #205
