### ISSUE TITLE
Frequency Schema Mapping

### ISSUE THREAD

**Issue by cchen818** [LibertyDSNP/spec#191]
As a publisher or consumer of DSNP data, I want to know what schemas are used for each announcement type.

Each announcement type will have a schema that will be mapped to the data structure.

The schemas are now all in https://github.com/LibertyDSNP/schemas

**Comment by shannonwells** [comment]
Questions: why is this "in progress" ?
What is the schemas repo for, does it have parquet and Avro schemas in it?

**Comment by wilwade** [comment]
I was working on it, but it was blocked until now.

Here is PR for part 1 with several open questions: https://github.com/LibertyDSNP/schemas/pull/1

**Comment by wilwade** [comment]
PR with the rest of the DSNP Schemas: https://github.com/LibertyDSNP/schemas/pull/4

**Comment by wilwade** [comment]
https://github.com/LibertyDSNP/schemas Merged.
