### ISSUE TITLE
Discussion: Key Recovery Process

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/spec#201]
As a user of frequency network, I want to be able to restore a lost cryptographic key (account key, private graph key), so I can access my account or data in the private graph.

Acceptance Criteria:
- [ ] The recovery process must be easy and straightforward
- [ ] The recovery process should be universal for recovering different types of keys

References:

- https://github.com/Liberty30/polkadot-experiments/issues/25#issuecomment-1026350463 
- https://github.com/LibertyDSNP/frequency/tree/main/designdocs
- [Why we need wide adoption of social recovery wallets](https://vitalik.ca/general/2021/01/11/recovery.html) 
- [An Off-Chain Solution for Social Recovery | by Web3Auth](https://medium.com/toruslabs/an-off-chain-solution-for-social-recovery-5f09c1ebd16b)

**Comment by aramikm** [comment]
That seems like a valid way to recover an account related key, To give access to MSA.

If we are using the considered recovery keys for encryption( like in private graph) this approach alone probably would not work , unless we have a way to recover the private graph data.

**Comment by wilwade** [comment]
Moving this to a Frequency/Wallet concern.
