### ISSUE TITLE
DIP-216 Add targetAnnouncementType to Update Announcements

### ISSUE THREAD

**Issue by wesbiggs** [LibertyDSNP/spec#216]
# Abstract

A Tombstone Announcement includes a `targetAnnouncementType` field, but an Update Announcement does not include a `targetAnnouncementType`.

The proposal is to add a targetAnnouncementType field to Update Announcements for parity with Tombstone Announcements.

# Motivation

1. Some services may not care about all announcement types, so having a target announcement type at the announcement level gives them an efficient way to skip irrelevant Update Announcements.
1. This field should be consistent for both Tombstone and Update Announcements.

# Specification Pull Request

Current change pull request:

# Rationale

Three alternatives were considered on the DSNP/Frequency Spec meeting on 8 Dec 2022.

1. Leave as is.
2. Remove `targetAnnouncementType` from Tombstone Announcement.
3. Add `targetAnnouncementType` to Update Announcement.

The preponderance of attendees were in favor of option 3.

# Backwards Compatibility

While this will change the data format for an Update Announcement, there are not yet any of these to contend with.

# Reference Implementation and/or Tests

The field should be added as specified to the reference implementation with appropriate additions or modifications of unit and integration tests.

# Security Considerations

No security implications.

# Dependencies

N/A

# References

N/A

# Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by wilwade** [comment]
Closed with #217
