### ISSUE TITLE
DIP-228 Remove Graph Change Announcement

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/spec#228]
# Abstract

Proposes the removal of the Graph Change announcement type.

# Motivation

DSNP Users need to be able to manage their social graph in much more complex and controlled ways than what is possible with the current Graph Change announcement.

# Specification Pull Request

#230

# Rationale

A forthcoming DIP will propose that the social graph be considered mutable state and be managed via Replace User Data and Get User Data Operations. By making these DSNP Operations, implementations are empowered to optimize storage and make opinionated decisions about scalability and efficiency.

Additional points in favor of removal include the inability to manage private connections via a public announcement, and the lack of need for, and arguably, personal data leakage due to, publishing long-lived information about connections which may change.

# Backwards Compatibility

Not backward compatible. Implementations should ignore any previous Graph Change announcements and use the new User Data operations instead. However, at this early stage in the DSNP project, there should be few if any orphaned announcements for implementations to deal with.

# Reference Implementation and/or Tests

None at this time.

# Security Considerations

Removing Graph Change Announcements in favor of mutable state operations should give users better control over the social graph, which can only be a good thing for security.

# Dependencies

None.

# References

None at this time.

# Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by wilwade** [comment]
Closed with #230
