### ISSUE TITLE
Discussion: Attestations-Lite

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/spec#272]
## If not, 
1. Is it appropriate to make an attestation an explicit part of DSNP?

## Specific use cases
The use cases are about a need to announce the existence of some type of document or created work as soon as possible after it has been created, to stave off alternate, and/or forged claims.  The attestation is simply "this thing exists on or before this ${timestamp}"

1. As someone who wishes to protect my claim to authorship, I want to announce the existence of a created work, using metadata and media of the work.
    i.  Metadata could include the author's name, its location at the time of the announcement, description, media type, an optional media URI (image or video or audio file, which is not required to remain accessible), and a checksum
3. As someone who wishes to protect my (private) estate plan, I want to announce the existence of the plan in its current form, using only metadata
    i.  Depending on need for privacy, metadata could include simply a checksum, or could include what type of document it is (living trust, will, estate plan, etc.) and names
4. As someone who has previously announced an estate plan, I want to announce an updated plan.
5. As a provider, I want to provide a much cheaper, more user-friendly, _user-owned_ and decentralized alternative to existing solutions for the above, by batch-announcing such attestations as a Provider on a DSNP-compliant platform.

In this system, I could also Tombstone an erroneous announcement, and I could conceivably self-announce updates as well, or easily switch to another provider for updates, say if the provider goes out of business.

Updates could be replies.

### Open Timestamp
@wesbiggs

**Comment by wesbiggs** [comment]
The proposed [External Content Attribute Set Announcement](https://github.com/LibertyDSNP/spec/blob/proposal/attributes-attestation/pages/DSNP/Types/ExternalContentAttributeSet.md) could be used to cover this case. 

- the Announcement is anchored to a specific announcement time (block), and may be batched;
- it references a Verifiable Credential by URL, hash, and attribute set type (corresponding to a JSON schema);
- the retrieved Verifiable Credential (which could be self-signed or signed by some witness/authority) contains metadata particular to the type of document and use case

Attribute Set Announcements can be Tombstoned, but not Updated, so the semantics of publishing a new estate plan (3) would be to tombstone the old version and announce a new version.
