### ISSUE TITLE
Fix 404 Not found error

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/spec#279]
Thanks for reporting an issue!

### Steps to reproduce
1. Go to https://spec.dsnp.org/Frequency/Identity.html#control-keys
2. Click on the first "MSA Pallet" link

### Expected behavior
A doc page on MSA pallet

### Actual behavior
404 error thrown

**Comment by wilwade** [comment]
This was fixed with https://github.com/LibertyDSNP/spec/pull/278, but it hasn't been deployed yet. @wesbiggs Deployment needed?
