### ISSUE TITLE
DIP-48 Activity Announcement Validations

### ISSUE THREAD

**Issue by rosalinekarr** [LibertyDSNP/spec#48]
# Summary

Add optional, logic-level validation specifications for [ActivityPub](https://www.w3.org/TR/activitypub/) content included in broadcast messages.

# Abstract

The [Activity Vocabulary](https://www.w3.org/TR/activitystreams-vocabulary/) specification includes several types for user activity content, like following someone or joining groups. Many client implementers will likely want to support these activity types, and in the interest of consistency across implementations, we should specify some standards for these types of events. Specifically, we may want to define validation for these events as they overlap with the DSNP specification such that only Activity Pub content with coincides with matching DSNP activity will be considered valid. For example, if a user posts an announcement that they've followed another user, they would have to actually follow that user via the DSNP graph specification for the announcement to be considered valid.

# Specification

The following is proposed for addition to the spec as a new `Validation.md` file under a new `Activity Content` directory:

```
# Activity Pub Content Validation

Specific types of DSNP messages may also include their own specific validation checks depending on the semantic purpose of the message type.
These specific validation checks follow:

## Broadcasts

1. All broadcast messages with a `"type"` field of `"Follow"` in the activity pub content must be preceded by a follow [Graph Change](/Messages/Overview#GraphChange) DSNP message with a followee matching the `"object"` field of the content.
1. All broadcast messages with a `"type"` field of `"Like"` or `"Dislike"` in their activity pub content must be preceded by a [Reaction](/Messages/Overview#Reaction) DSNP message referring to the same object, i.e. that the `URI` message field of DSNP message identified by the `inReplyTo` field of the reaction is identical to the `"object"` field of the like or dislike activity pub content.
1. All broadcast messages with a `"type"` field of `"Undo"` must include an `"object"` field with either a valid DSNP identifier referring to a previously announced broadcast message or a URI matching the URI of a previously announced broadcast event by the user.

## Replies & Reactions

1. All reply and reaction messages must include an `inReplyTo` field identifying an existing DSNP message.
1. All reply and reaction messages must be from and signed by a user, the replier, for which the user who posted the original content referred to in the `inReplyTo` field has never previously published a broadcast message with an activity pub content `"type"` field of `"Block"` and `"object"` field containing the string `dsnp://` followed by the user id of the replier, thereby indicating that the original poster has previously blocked the replier.
```

# Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by rosalinekarr** [comment]
# Notes following May 20th, 2021 spec discussion meeting

* We want to add a DSNP Message Type for Profiles which requires a linked `"Profile"` type Activity Pub object.
* We may want to add more DSNP message types in the future for things like Block, Like, Undo, etc.
* As such, we should limit Broadcast DSNP message types to a subset of Activity Pub types for now.
* Those types will likely be `"Audio"`, `"Image"`, `"Note"` and `"Video"`, but we need further discussion.

**Comment by wilwade** [comment]
In various ways most of this has been incorporated with other spec changes. If pieces were missed, please open a new DIP.
