### ISSUE TITLE
DIP-50 Intellectual Property and Digital Rights Management

### ISSUE THREAD

**Issue by rosalinekarr** [LibertyDSNP/spec#50]
# Summary

Add specifications for licensed content and other exemptions to legal restrictions.

# Abstract

Archivists, indexers and content hosts will likely be required to remove certain content due to local laws in their given legal jurisdictions. This can create frustrations for users abiding by the law when their content is [mistakenly removed despite them having all the necessary licensing or other legal exemptions](https://www.eff.org/wp/unfiltered-how-youtubes-content-id-discourages-fair-use-and-dictates-what-we-see-online). To mitigate this problem in the DSNP, we should implement an extension of the Activity Pub standard to allow users to acknowledge content potentially violating legal restrictions and provide explanations or proof of their legal exemption.

# Specification

The following is proposed for addition to the spec as a new `Licensing.md` file under a new `Extensions` directory:

```
### Copyright & Licensing

Implementations may also choose or be required by law to invalidate content identified as violating certain laws, such as intellectual property, in the end-user's specific legal jurisdiction.
These implementations may use content fingerprinting, shared lists or other methods to identify this content.
This document will not define any standards for these methods except that before removing any potentially violating content implementers must verify that the offending content does not include proof of legal exemption, such as paid licensing, in the activity pub content of the message.

These legal exceptions must be listed under an additional content field named `"licensing"` which may include either a URI pointing to the appropriate proof, an object to be defined by the enforcing legal body or an array consisting of multiple instances of either.
For example, here is a sample activity pub object with fictional licensing:

/```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Video",
  "name": "Excerpt of Yankees vs Nationals Game 2021",
  "url": "http://sportsblog.com/yankeesnationals2021.mkv",
  "duration": "5M",
  "licensing": [
    "https://mlb.com/licensing/sportsblogcom.json",
    {
      "authority": "ESPN",
      "type": "paid",
      "licensee": "SportsBlog.com",
      "proof": "c3RyaW5naBc6453=w-9sSAw4naBc8533="
    }
  ]
}
/```
```

# Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by wilwade** [comment]
Archive
