### ISSUE TITLE
DSNPType enum is out of spec

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/spec#71]
In the SDK, we have

```
export enum DSNPType {
  Broadcast,
  Reply,
  Reaction,
}
```

But in the spec, these have completely different values, and there are additional ones as well:
http://spec.projectliberty.io/Messages/Types

These two need to be reconciled. We aren't supporting everything that's in the spec but we did have a discussion to put Profile type back in.

Additionally, in src/batch/actionType there are enums that are basically the same thing. We need to decide which of these to use, but this enum doesn't belong in batch either way.

**Comment by wilwade** [comment]
Fixed in https://github.com/LibertyDSNP/sdk-ts/pull/57
