### ISSUE TITLE
Resolve "actionType" name collision in spec + sdk

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/spec#72]
We use `actionType` to indicate the type of DSNP announcement, and also for the GraphChange follow/unfollow field. We should change one, probably GraphChange field name, as that would be easiest. I propose "changeType". Since I'm (@shannonwells) working on #177940101 that's what I'll use there for now.

This definitely needs to change because the Parquet schema needs unique keywords, and we are including DSNP announcement type, `actionType` as a column stored in batch files.

Both the DSNP spec and the SDK would need to be updated. Also be aware that the Parquet schema in the SDK may need to be updated too.

**Comment by wilwade** [comment]
@shannonwells I think actionType on the DSNP Announcement was renamed to DSNPType right?

**Comment by wilwade** [comment]
It is now type on the DSNP message interface: https://github.com/LibertyDSNP/sdk-ts/blob/main/src/messages/messages.ts#L21

Changing it to match https://github.com/LibertyDSNP/sdk-ts/issues/46
