### ISSUE TITLE
How do I delete content (and let people know)?

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/spec#80]
Deleting content is not addressed in the spec, but I think it should be.

Currently:
- Some things cannot be "deleted": Reactions
- Some things can be undone: Follow -> Unfollow
- Some things can be updated: Profile
- Some things cannot be deleted, but the referenced content can be: Broadcast, Reply (Although nothing asks caching services to remove it)

## Questions
- Should reactions be able to be undone?
- How can Broadcasts/Replies be retracted?
- How can edits propagate?

## Previous Discussion Thoughts
- Announcement type of "Metadata" that could include updated contentHash or tombstone flag
- 404 body content (although that wouldn't fix it for caches)
- Leverage some form of "self" moderation flag

**Comment by wilwade** [comment]
## Spec Discussion Notes
- Activity Pub has some standards for deleting and updating perhaps we should see if we can use it
- Flag content as deleted or a date for deletion
- What about censorship? Is it the same as deleting?
  - #49 might be related
- Metadata might meet other use cases
  - Lag time matters
- Do we need to care about cache busting?
  - Users care
  - Edit case (J: Everyday I hear people saying they want a **** edit button)
  - J: We don't control the caches. Are there behaviors and standards we want to encourage and even potentially enforce (somehow) in these areas we don't control? (Forum post: https://forums.projectliberty.io/t/what-non-tech-forced-standards-might-we-want/48)
- Metadata appears to capture a lot of the Broadcast/Reply case
- What about Reactions?
  - Applications should have a sending lag to catch some undo cases
  - J: Expectation of ability to undo a reaction
  - S: Could we just retrain people to think more in a real world (aka you cannot retract sound waves irl)
  - General feeling is we still want some sort of a retraction
  - R to add a new issue around retracting reactions
- Documentation around Client "Best Practices" (Give users a chance to undo ala sending email)
- Options for edits/deletes and cache busting:
  - Use use Activity Pub and replies - TODO: What would this look like?
  - Metadata (generic uses) announcement type
  - Custom announcement type specific to edits and deletes

**Comment by jvasile** [comment]
There is one pretty good argument against allowing editing posts (but this doesn't apply to retracting reactions).  A malicious user could post a picture of snuggling otters drifting on rainbows.  Nobody could resist that, and just after the post hits peak sharing all over the net, they edit the post to replace the picture with one of otters teaching kids that 2+2=5.  Those monsters!  Nobody would have reshared or 'liked' otters spreading misinformation, but here it is at the top of every feed in the world.

Maybe the edit button should be more like a "add more words/media to a post" button.  This way you can correct the fact you got wrong by saying "whoa I shoulda checked snopes" but you can't convince the system to treat harmful content like feelgood memes.

**Comment by shannonwells** [comment]
Media companies formerly referred to as newspapers and magazines still publish errata and retractions so it's not much different from that, and before you could do that some people would not edit the data but add an "[Edit] &lt;corrected text&gt;" comment.  Many people still do this rather than changing their original post.

**Comment by jvasile** [comment]
@shannonwells I really like that gloss!
