### ISSUE TITLE
Broken link to Developer Portal on spec.dsnp.org

### ISSUE THREAD

**Issue by allisonrandal** [LibertyDSNP/spec#91]
In the file doczrc.js, there's a link for "↩ Developer Portal" (which shows up in the sidebar on spec.dsnp.org), and it links to the URL "https://www.projectliberty.io/#/developer-portal". That page doesn't exist anymore, the new link for the Developer Portal is "https://www.dsnp.org/developer-portal/".

**Comment by wilwade** [comment]
Closed by #93
