### ISSUE TITLE
URL vs URI

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/spec#95]
Currently the spec has both URI and URL used interchangeably. I don't think it should.

### Steps to reproduce
Look through the spec and see both URI and URL

### Expected behaviour
Only one? or at least reasons to use one over the other?

### Actual behaviour
We see both

### Any other comments?
The whitepaper used URI.

**Comment by shannonwells** [comment]
I think we should use URL.   The entity we're talking about is the locator for a file, not a name or any other type of "indicator," which makes it specifically a URL, not just the more general URI.  I really like [this explanation](https://danielmiessler.com/study/difference-between-uri-url/)

**Comment by wilwade** [comment]
Notes from Weekly Spec Meeting 2021-07-01

General agreement with the comment from @shannonwells.

What if we add other protocols other than https? Say ipfs? A: URL still applies.

TODO: Update the spec to URL everywhere and also anywhere in the contacts or sdk.
